VIDEO_PATH = "1.mp4"
MODEL_PATH = "yolov8n-seg.pt"
JSON_OUTPUT_PATH = "output.json"
PERF_DETECTOR_IMGSZ = 576
PERF_DETECTION_INTERVAL = 2
PERF_LANE_INTERVAL = 2
PERF_VISIBILITY_INTERVAL = 2
PERF_TRACKER_PREDICTION_AGE = 1
PERF_LANE_MAX_WIDTH = 1280
PERF_DETECTOR_CLASSES = [0, 1, 2, 3, 5, 7, 9, 11]
DISPLAY_WINDOW_WIDTH = 800
DISPLAY_WINDOW_HEIGHT = 600
BIRDVIEW_WINDOW_WIDTH = 920
BIRDVIEW_WINDOW_HEIGHT = 620
BIRDVIEW_MAX_DISTANCE = 40
BIRDVIEW_PANEL_WIDTH = 280
BIRDVIEW_LANE_SMOOTHING_ALPHA = 0.18
BIRDVIEW_OBJECT_SMOOTHING_ALPHA = 0.30
BIRDVIEW_LANE_MEMORY_FRAMES = 12
BIRDVIEW_DEFAULT_LANE_WIDTH_TOP = 0.30
BIRDVIEW_DEFAULT_LANE_WIDTH_BOTTOM = 0.82
ROAD_CONTEXT_FALLBACK_LANE_WIDTH_RATIO = 0.36
ROAD_CONTEXT_EGO_OVERLAP_THRESHOLD = 0.35
ROAD_CONTEXT_ADJACENT_LANE_LIMIT = 2.6
ROAD_CONTEXT_HEADING_CLAMP = 0.35
CAMERA_HEIGHT_M = 1.45
ROAD_CONTEXT_REAL_LANE_WIDTH_M = 3.6
ROAD_CONTEXT_DEFAULT_HORIZON_RATIO = 0.38
ROAD_CONTEXT_HORIZON_SMOOTHING_ALPHA = 0.16
ROAD_CONTEXT_DISTANCE_SMOOTHING_ALPHA = 0.28
ROAD_CONTEXT_CURVE_SAMPLE_COUNT = 11
ROAD_CONTEXT_CURVE_MAX_LATERAL_M = 4.5
ROAD_CONTEXT_CURVE_SMOOTHING_ALPHA = 0.20
ROAD_CONTEXT_MIN_CLOSING_SPEED_MPS = 0.25
ROAD_CONTEXT_TTC_MAX_S = 12.0
ROAD_CONTEXT_MAX_DISTANCE_DELTA_PER_FRAME_M = 0.70
ROAD_CONTEXT_MAX_DISTANCE_DELTA_LOW_VIS_M = 0.45
DECISION_FOLLOW_TTC_REDUCED_ENTER = 6.4
DECISION_FOLLOW_TTC_REDUCED_EXIT = 7.6
DECISION_FOLLOW_TTC_COAST_ENTER = 4.8
DECISION_FOLLOW_TTC_COAST_EXIT = 5.8
DECISION_FOLLOW_TTC_LIGHT_BRAKE_ENTER = 3.4
DECISION_FOLLOW_TTC_LIGHT_BRAKE_EXIT = 4.1
DECISION_FOLLOW_TTC_PROGRESSIVE_BRAKE_ENTER = 2.4
DECISION_FOLLOW_TTC_PROGRESSIVE_BRAKE_EXIT = 2.9
DECISION_FOLLOW_TTC_MAXIMUM_BRAKE_ENTER = 1.65
DECISION_FOLLOW_TTC_MAXIMUM_BRAKE_EXIT = 2.05
DECISION_FOLLOW_TTC_EMERGENCY_BRAKE_ENTER = 1.05
DECISION_FOLLOW_TTC_EMERGENCY_BRAKE_EXIT = 1.35
DECISION_FOLLOW_DISTANCE_REDUCED_ENTER = 22.0
DECISION_FOLLOW_DISTANCE_REDUCED_EXIT = 25.0
DECISION_FOLLOW_DISTANCE_COAST_ENTER = 14.0
DECISION_FOLLOW_DISTANCE_COAST_EXIT = 16.0
DECISION_FOLLOW_DISTANCE_LIGHT_BRAKE_ENTER = 11.5
DECISION_FOLLOW_DISTANCE_LIGHT_BRAKE_EXIT = 13.2
DECISION_FOLLOW_DISTANCE_PROGRESSIVE_BRAKE_ENTER = 8.5
DECISION_FOLLOW_DISTANCE_PROGRESSIVE_BRAKE_EXIT = 9.8
DECISION_FOLLOW_DISTANCE_MAXIMUM_BRAKE_ENTER = 6.1
DECISION_FOLLOW_DISTANCE_MAXIMUM_BRAKE_EXIT = 7.0
DECISION_FOLLOW_DISTANCE_EMERGENCY_BRAKE_ENTER = 4.4
DECISION_FOLLOW_DISTANCE_EMERGENCY_BRAKE_EXIT = 5.1
DECISION_FOLLOW_REL_SPEED_REDUCED_ENTER = -0.10
DECISION_FOLLOW_REL_SPEED_REDUCED_EXIT = -0.45
DECISION_FOLLOW_REL_SPEED_COAST_ENTER = 0.20
DECISION_FOLLOW_REL_SPEED_COAST_EXIT = -0.15
DECISION_FOLLOW_REL_SPEED_LIGHT_BRAKE_ENTER = 0.45
DECISION_FOLLOW_REL_SPEED_LIGHT_BRAKE_EXIT = 0.05
DECISION_FOLLOW_REL_SPEED_PROGRESSIVE_BRAKE_ENTER = 0.85
DECISION_FOLLOW_REL_SPEED_PROGRESSIVE_BRAKE_EXIT = 0.35
DECISION_FOLLOW_REL_SPEED_MAXIMUM_BRAKE_ENTER = 1.25
DECISION_FOLLOW_REL_SPEED_MAXIMUM_BRAKE_EXIT = 0.65
DECISION_FOLLOW_REL_SPEED_EMERGENCY_BRAKE_ENTER = 1.70
DECISION_FOLLOW_REL_SPEED_EMERGENCY_BRAKE_EXIT = 0.95
DECISION_SPEEDOMETER_MAX_KMH = 130.0
DECISION_SPEED_INITIAL_KMH = 52.0
DECISION_SPEED_RESPONSE_UP_KMHPS = 7.0
DECISION_SPEED_RESPONSE_DOWN_KMHPS = 18.0
RENDER3D_WINDOW_WIDTH = 1100
RENDER3D_WINDOW_HEIGHT = 720
RENDER3D_MAX_DISTANCE = 55
RENDER3D_LANE_WIDTH = 3.6
RENDER3D_OBJECT_SMOOTHING_ALPHA = 0.24
RENDER3D_ROAD_HEADING_SMOOTHING_ALPHA = 0.12
RENDER3D_ROAD_CURVE_SMOOTHING_ALPHA = 0.16
RENDER3D_CAMERA_HEIGHT = 8.2
RENDER3D_CAMERA_BACK_Z = 18.0
RENDER3D_CAMERA_LOOKAHEAD = 24.0
RENDER3D_EGO_Z = 6.0
RENDER3D_FAR_PLANE = 180.0
BIRDVIEW_ROAD_HEADING_SMOOTHING_ALPHA = 0.14
BIRDVIEW_ROAD_CURVE_SMOOTHING_ALPHA = 0.18
TRAFFIC_LIGHT_MIN_BOX_SIZE = 10
TRAFFIC_LIGHT_MIN_SATURATION = 70
TRAFFIC_LIGHT_MIN_VALUE = 80
TRAFFIC_LIGHT_MIN_ACTIVE_PIXELS = 6
TRAFFIC_LIGHT_SCORE_MARGIN = 1.12
VISIBILITY_ANALYSIS_WIDTH = 320
VISIBILITY_SMOOTHING_ALPHA = 0.18
VISIBILITY_DIM_BRIGHTNESS_THRESHOLD = 0.40
VISIBILITY_NIGHT_BRIGHTNESS_THRESHOLD = 0.26
VISIBILITY_FOG_CONTRAST_THRESHOLD = 0.22
VISIBILITY_FOG_SATURATION_THRESHOLD = 0.28
VISIBILITY_FOG_EDGE_DENSITY_THRESHOLD = 0.055
VISIBILITY_LOW_VISIBILITY_SCORE_THRESHOLD = 0.62
VISIBILITY_CLAHE_CLIP_LIMIT = 2.4
VISIBILITY_CLAHE_TILE_SIZE = 8
VISIBILITY_DIM_GAMMA = 0.84
VISIBILITY_NIGHT_GAMMA = 0.68
VISIBILITY_FOG_UNSHARP_AMOUNT = 0.22

JSON_INTERVAL = 0.5
DETECTION_CONFIDENCE = 0.35
DETECTION_CONFIDENCE_VISIBILITY_FLOOR = 0.24

VEHICLE_CLASSES = {"car", "truck", "bus", "motorcycle"}
PERSON_CLASSES = {"person", "bicycle"}

# lane ROI
LANE_TOP_CUT_RATIO = 0.57
LANE_SIDE_MARGIN_RATIO = 0.01
LANE_BOTTOM_MARGIN_RATIO = 0.13

# lane filtering
LANE_CANNY_LOW = 50
LANE_CANNY_HIGH = 150
LANE_CANNY_LOW_MIN = 34
LANE_CANNY_HIGH_MAX = 200
LANE_HOUGH_THRESHOLD = 50
LANE_MIN_LINE_LENGTH = 100
LANE_MAX_LINE_GAP = 50
LANE_MIN_ABS_SLOPE = 0.3
LANE_MAX_FILTERED_LINES = 32
LANE_MAX_FILTERED_LINES_LOW_VIS = 20
LANE_MARKING_WHITE_THRESHOLD = 178
LANE_MARKING_WHITE_THRESHOLD_LOW_VIS = 148
LANE_MARKING_YELLOW_S_MIN = 70
LANE_MARKING_YELLOW_V_MIN = 70

# distance estimation
REAL_HEIGHTS = {
    "person": 1.70,
    "car": 1.50,
    "truck": 3.20,
    "bus": 3.10,
    "motorcycle": 1.40,
    "bicycle": 1.20,
    "stop sign": 0.75,
    "traffic light": 0.90
}

REAL_WIDTHS = {
    "person": 0.45,
    "car": 1.80,
    "truck": 2.50,
    "bus": 2.55,
    "motorcycle": 0.80,
    "bicycle": 0.60
}

FOCAL_LENGTH = 900
TRACK_SEGMENT_IOU_THRESHOLD = 0.15
DISTANCE_SMOOTHING_ALPHA = 0.35
DECISION_VISIBILITY_DIM_SPEED_CAP_KMH = 54.0
DECISION_VISIBILITY_NIGHT_SPEED_CAP_KMH = 48.0
DECISION_VISIBILITY_FOG_SPEED_CAP_KMH = 40.0
DECISION_VISIBILITY_LOW_SPEED_CAP_KMH = 28.0
